### ISSUE TITLE
Ajuste no projeto: Erro de compilação

### ISSUE THREAD

**Issue by oliveiralex** [gigliozzi/github-user-search#1]
Olá William,

Meu nome é Alexandre e estou corrigindo o seu projeto. O mesmo foi aceito, parabéns! Só tem um ponto pra ficar 100%. Quando fui executar, deu um erro de compilação. Aparentemente o nome do arquivo App.css não está sendo importado corretamente no arquivo App.tsx.

Depois confere certinho e faça os ajustes assim que possível!

Abraço

**Comment by gigliozzi** [comment]
Olá Alex,

Obrigado pelo feedback! Fiz um novo commit com a correção 👍 

Abraço.

**Comment by oliveiralex** [comment]
Obrigado William!

Abraço
